[package]
name = "montmort_number"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "CC0-1.0"
publish = false

[dev-dependencies]
pretty_assertions = "0.6.1"
