[package]
name = "library-checker"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "CC0-1.0"
publish = false

[dependencies]
ac-library-rs-parted-modint = { git = "https://github.com/qryxip/ac-library-rs-parted" }
input = { path = "../../crates/input" }
montmort_number = { path = "../../crates/montmort_number" }
output = { path = "../../crates/output" }
tonelli_shanks = { path = "../../crates/tonelli_shanks" }
