[package]
name = "library-checker"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "CC0-1.0"
publish = false

[dependencies]
ac-library-rs-parted-modint = { git = "https://github.com/qryxip/ac-library-rs-parted" }
qryxips-competitive-programming-library-buffered-print = { version = "0.0.0", path = "../../crates/io/buffered_print" }
qryxips-competitive-programming-library-input = { path = "../../crates/io/input" }
qryxips-competitive-programming-library-montmort-number = { path = "../../crates/integer/montmort_number" }
qryxips-competitive-programming-library-tonelli-shanks = { path = "../../crates/modulo/tonelli_shanks" }
