[package]
name = "yukicoder"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
license = "CC0-1.0"
publish = false

[dependencies]
qryxips-competitive-programming-library-input = { path = "../../crates/io/input" }
qryxips-competitive-programming-library-partition-point = { path = "../../crates/partition_point" }
