test-suite = "{{ manifest_dir }}/testcases/{{ bin_alias }}.yml"

[template]
src = '''
fn main() {
    todo!();
}
'''

[add]
url = "https://yukicoder.me/problems/no/{{ args[0] }}"
bin-name = '{{ args[0] }}'

[test]
profile = "release"

[submit.transpile]
kind = "command"
args = ["cargo", "equip", "--resolve-cfgs", "--remove", "docs", "--minify", "libs", "--rustfmt", "--check", "--bin", "{{ bin_name }}"]
