name: CI

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup `stable-x86_64-unknown-linux-gnu`
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          default: true
          profile: minimal
          components: rustfmt,clippy

      - name: Setup `1.41.0-x86_64-unknown-linux-gnu`
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.41.0-x86_64-unknown-linux-gnu
          default: false
          profile: minimal
          components: rustfmt,clippy

      - name: Setup `1.44.1-x86_64-unknown-linux-gnu`
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.44.1-x86_64-unknown-linux-gnu
          default: false
          profile: minimal
          components: rustfmt,clippy

      - name: cargo-fmt (`lib`)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./lib/Cargo.toml -- --check
          toolchain: stable

      - name: cargo-fmt (`verification/library-checker`)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./verification/library-checker/Cargo.toml -- --check
          toolchain: 1.41.0

      - name: cargo-fmt (`verification/yukicoder`)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./verification/yukicoder/Cargo.toml -- --check
          toolchain: 1.44.1

      - name: cargo-clippy (`lib`)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./lib/Cargo.toml -- -D warnings
          toolchain: stable

      - name: cargo-clippy (`verification/library-checker`)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./verification/library-checker/Cargo.toml -- -D warnings
          toolchain: 1.41.0

      - name: cargo-clippy (`verification/yukicoder`)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./verification/yukicoder/Cargo.toml -- -D warnings
          toolchain: 1.44.1

  verify:
    name: Verify
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout (v1)
        uses: actions/checkout@v1

      - name: Setup Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          default: true
          profile: minimal
          components: rustfmt

      - name: Setup Rust (1.41.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.41.0-x86_64-unknown-linux-gnu
          default: false
          profile: minimal
          components: rustfmt

      - name: Setup Rust (1.44.1)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.44.1-x86_64-unknown-linux-gnu
          default: false
          profile: minimal
          components: rustfmt

      - name: Install cargo-equip
        run: |
          VERSION=0.3.0
          wget "https://github.com/qryxip/cargo-equip/releases/download/v$VERSION/cargo-equip-v$VERSION-x86_64-unknown-linux-gnu.tar.gz"
          tar xzvf "./cargo-equip-v$VERSION-x86_64-unknown-linux-gnu.tar.gz" -C /tmp/
          echo "::add-path::/tmp/cargo-equip-v$VERSION-x86_64-unknown-linux-gnu"

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install oj-verify
        run: pip3 install -U online-judge-verify-helper

      - name: oj-verify
        run: oj-verify all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
