name: CI

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0-x86_64-unknown-linux-gnu
          target: wasm32-unknown-unknown
          default: true
          profile: minimal
          components: rustfmt,clippy

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: cargo-fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo-fmt (proc-macro/*)
        run: ls ./proc-macros/*/Cargo.toml | xargs -n 1 -I % cargo fmt --manifest-path % -- --check

      - name: cargo-clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets --all-features -- -D warnings

      - name: cargo-clippy (proc-macro/*)
        run: ls ./proc-macros/*/Cargo.toml | xargs -n 1 -I % cargo clippy --manifest-path % -- -D warnings

      - name: cargo-test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --exclude qryxip-competitive --no-fail-fast

  verify:
    name: Verify
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout (v1)
        uses: actions/checkout@v1

      - name: Setup Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-x86_64-unknown-linux-gnu
          target: wasm32-unknown-unknown
          default: false
          profile: minimal

      - name: Setup Rust (1.42.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0-x86_64-unknown-linux-gnu
          target: wasm32-unknown-unknown
          default: true
          profile: minimal

      #- name: Install cargo-udeps
      #  uses: actions-rs/install@v0.1
      #  with:
      #    crate: cargo-udeps
      #    use-tool-cache: true
      - name: Install cargo-udeps
        run: |
          version="$(curl https://crates.io/api/v1/crates/cargo-udeps | jq -r '.crate.max_version')"
          wget "https://github.com/est31/cargo-udeps/releases/download/v$version/cargo-udeps-v$version-x86_64-unknown-linux-gnu.tar.gz"
          tar xzvf "./cargo-udeps-v$version-x86_64-unknown-linux-gnu.tar.gz" -C /tmp/
          echo "/tmp/cargo-udeps-v$version-x86_64-unknown-linux-gnu" >> $GITHUB_PATH

      - name: Setup Python (latest)
        uses: actions/setup-python@v1

      - name: Install oj-verify
        run: pip3 install git+https://github.com/online-judge-tools/verification-helper.git

      - name: oj-verify
        run: oj-verify all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
